"""empty message

Revision ID: 2f3c81325c2b
Revises: 57fe11afb3d3
Create Date: 2025-09-22 11:25:01.891679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f3c81325c2b'
down_revision = '57fe11afb3d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_column('criado_em')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criado_em', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
